version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gocritic
    - revive
    - copyloopvar
    - errorlint
    - exhaustive
    - gochecknoinits
    - goconst
    - godot
    - sqlclosecheck
    - wastedassign
    - forcetypeassert
  disable:
    - errcheck
    - gosec
    - gochecknoglobals

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment

  misspell:
    locale: US

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 3

  exclude-rules:
    # Allow fmt.Printf in main.go (CLI output)
    - path: cmd/ccbell/main.go
      linters:
        - forbidigo

    # Testing patterns are different - skip specific linters for tests
    - path: _test\.go
      linters:
        - gocritic
        - revive
