version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gocritic
    - revive
    - copyloopvar
    - errorlint
    - exhaustive
    - gochecknoinits
    - goconst
    - godot
    - sqlclosecheck
    - wastedassign
    - forcetypeassert
  disable:
    - errcheck
    - gosec
    - gochecknoglobals

issues:
  exclude_use_default: false
